const {chromium}=require('playwright');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:390,height:844}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route(/script\.google\.com/,route=>route.abort());
  await page.addInitScript(()=>{
    localStorage.setItem('ben_tracker_v12_settings',JSON.stringify({sharedGoal:{goal_version:1,age:35,sex:'male',height_in:68,current_weight_lb:165,physique_goal:'maintain',calorie_target:2000,protein_min_g:124,planned_strength_workouts_week:2,goal_started_at:new Date().toISOString()},workoutProgram:null}));
  });
  await page.goto(pathToFileURL(path.join(__dirname,'..','index.html')).href);
  await page.waitForTimeout(1000);
  if(errors.length)throw new Error(errors.join('\n'));
  await page.locator('#openPlanBtn').click({force:true});
  await page.getByText('Set up your workout',{exact:true}).waitFor();
  if(!await page.locator('#planBackdrop.workoutFullscreen').count())throw new Error('Workout setup is not full screen');
  await page.locator('[data-choice="1"]').click();await page.locator('#workoutSetupNext').click();
  await page.locator('[data-choice="hip width, toes forward"]').click();await page.locator('#workoutSetupNext').click();
  await page.locator('#workoutSetupNext').click();
  await page.locator('#workoutSetupInput').fill('0');await page.locator('#workoutSetupNext').click();
  await page.locator('#workoutSetupNext').click();
  await page.locator('#workoutSetupNext').click();
  await page.locator('#beginCalibration').click();
  await page.getByText('Low-Incline Dumbbell Press',{exact:true}).first().waitFor();
  if(!await page.locator('.calibrationTips[open]').count())throw new Error('Calibration form tips were hidden');
  await page.locator('#calWeight').fill('30');
  await page.locator('#calReps').fill('12');
  await page.locator('[data-difficulty="aboutRight"]').click();
  await page.locator('#countCalibrationSet').click();
  const program=await page.evaluate(()=>JSON.parse(localStorage.getItem('ben_tracker_v12_settings')).workoutProgram);
  if(program.rdlStance!==program.squatStance)throw new Error('Hinge stance did not reuse squat stance');
  if(program.workingWeights.press_incline!==30)throw new Error('Calibration weight was not saved');
  if(!await page.locator('#planBackdrop.workoutFullscreen').count())throw new Error('Workout tracker is not full screen');
  if(!await page.locator('.workoutTips[open]').count())throw new Error('Workout form tips were hidden');
  if(await page.locator('.wpWeight:visible').count()!==1||await page.locator('.wpRep:visible').count()!==1)throw new Error('Tracker must show one set at a time');
  await page.locator('#nextExercise').click();
  if(!await page.getByText('Enter your clean reps before saving this set.').count())throw new Error('Blank set was allowed to advance');
  await page.locator('.wpRep:visible').fill('11');
  await page.locator('.workoutLoadOverride').click();
  await page.locator('.wpWeight:visible').fill('');
  await page.locator('#nextExercise').click();
  if(!await page.getByText('Enter weight before saving this set.').count())throw new Error('Set without weight was allowed to advance');
  await page.locator('.wpWeight:visible').fill('30');
  await page.locator('#nextExercise').click();
  await page.locator('.wpRep:visible').fill('10');
  await page.locator('#nextExercise').click();
  await page.locator('#nextExercise').click();
  await page.getByText('Goblet Squat',{exact:true}).first().waitFor();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('ben_tracker_v12_store')));
  if(!Object.values(stored.days).some(day=>Object.values(day.workoutLog||{}).some(log=>log.exerciseId==='press_incline'&&log.setReps[0]==='12'&&log.setReps[1]==='11')))throw new Error('Press calibration set did not persist locally');
  await page.locator('#closePlanBtn').click();
  await page.locator('#openPlanBtn').click({force:true});
  await page.getByText('Goblet Squat',{exact:true}).first().waitFor();
  if(await page.locator('#beginCalibration').count())throw new Error('Partial calibration did not resume');
  await page.locator('#closePlanBtn').click();
  await page.locator('#bw').fill('165.6');
  await page.locator('#saveWeightBtn').click();
  const weightMessage=await page.locator('#weightEntryStatus').textContent();
  if(!/Daily weight logged|Saved on this device/.test(weightMessage))throw new Error(`Unexpected weight confirmation: ${weightMessage}`);
  await page.locator('#typeFoodBtn').click();
  await page.locator('#foodCaptureText').fill('Banana medium');
  await page.locator('#saveFoodCaptureBtn').click();
  if(await page.locator('#foodCaptureBackdrop.show').count())throw new Error('Food dialog did not close immediately');
  await page.getByText('Banana medium',{exact:true}).first().waitFor();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser smoke passed');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
