const {chromium}=require('playwright');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:390,height:844}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route(/script\.google\.com/,route=>route.abort());
  await page.addInitScript(()=>{
    localStorage.setItem('ben_tracker_v12_settings',JSON.stringify({sharedGoal:{goal_version:1,age:35,sex:'male',height_in:68,current_weight_lb:165,physique_goal:'maintain',calorie_target:2000,protein_min_g:124,planned_strength_workouts_week:2,goal_started_at:new Date().toISOString()},workoutProgram:null}));
  });
  await page.goto(pathToFileURL(path.join(__dirname,'..','index.html')).href);
  await page.waitForTimeout(1000);
  if(errors.length)throw new Error(errors.join('\n'));
  await page.locator('#openPlanBtn').click({force:true});
  await page.getByText('Set up your workout',{exact:true}).waitFor();
  await page.locator('#wpBench').selectOption('1');
  await page.locator('#wpSquatStance').selectOption('hip width, toes forward');
  await page.locator('#wpPullups').fill('0');
  await page.locator('#wpRdlStance').selectOption('hip width, toes forward');
  await page.locator('#wpDbIncrement').fill('5');
  await page.locator('#wpBarIncrement').fill('5');
  await page.locator('#wpCableIncrement').fill('5');
  await page.locator('#wpAssistIncrement').fill('5');
  await page.locator('#wpSave').click();
  await page.getByText('Low-Incline Dumbbell Press',{exact:true}).first().waitFor();
  await page.locator('.wpWeight').first().fill('35');
  await page.locator('.wpRep').first().fill('10');
  await page.locator('#nextExercise').click();
  await page.getByText('Goblet Squat',{exact:true}).first().waitFor();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('ben_tracker_v12_store')));
  if(!Object.values(stored.days).some(day=>Object.values(day.workoutLog||{}).some(log=>log.exerciseId==='press_incline'&&log.setReps[0]==='10')))throw new Error('Press set did not persist locally');
  await page.locator('#closePlanBtn').click();
  await page.locator('#bw').fill('165.6');
  await page.locator('#saveWeightBtn').click();
  const weightMessage=await page.locator('#weightEntryStatus').textContent();
  if(!/Daily weight logged|Saved on this device/.test(weightMessage))throw new Error(`Unexpected weight confirmation: ${weightMessage}`);
  await page.locator('#typeFoodBtn').click();
  await page.locator('#foodCaptureText').fill('Banana medium');
  await page.locator('#saveFoodCaptureBtn').click();
  if(await page.locator('#foodCaptureBackdrop.show').count())throw new Error('Food dialog did not close immediately');
  await page.getByText('Banana medium',{exact:true}).first().waitFor();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser smoke passed');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
